"""Add is_public field to Form model

Revision ID: 611352dcebcd
Revises: d1b3c50947ae
Create Date: 2025-11-02 18:26:44.228330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611352dcebcd'
down_revision = 'd1b3c50947ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
